name: knc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  image_picker: ^1.0.3
  mailer: ^6.2.0
  cached_network_image: ^3.0.0 # Use the latest stable version
  supabase_flutter: ^2.0.0
  photo_view: ^0.15.0
  url_launcher: ^6.0.15
  permission_handler: ^11.3.1
  file_picker: ^8.1.3
  shared_preferences: ^2.0.15  
  webview_flutter: ^4.10.0
  http_parser: ^4.0.2
  font_awesome_flutter: 10.7.0
  google_maps_flutter: ^2.2.2
  flutter_slidable: ^3.1.1
  connectivity_plus: ^6.1.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
